[package]
name = "cliapp"
version = "0.1.0"
authors = ["nel417 <n1ck@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
